version: "3"

services:
  server:
    container_name: blog_app_node
    build: "."

    depends_on:
      - db

    links:
      - db

    env_file:
      - .env

    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9229:9229"

    volumes:
      - .:/usr/app
      - ./node_modules:/usr/app/node_modules

    networks:
      - host

    restart: unless-stopped

  db:
    image: mongo:latest

    container_name: blog_app_mongo

    ports:
      - ${DB_PORT}:${DB_PORT}:27017

    volumes:
      - ./dbdata:/data/db

    networks:
      - host

    restart: unless-stopped

networks:
  host:
    driver: bridge

volumes:
  dbdata:
  node_modules:
